= Trabajo Práctico de Base de Datos 

=== Integrantes del Grupo 

Carlos Figueroa <lumusika@gmail.com>

Alan Kaneman <alan.knm1@gmail.com>

Maximiliano Gamarra <maxilgstylus@gmail.com>

=== Docentes de la Materia

Hernán Czemerinski 

Hernán Rondelli

(COM-01)

=== Fecha de Entrega: {docdate}

:numbered:
:source-highlighter: highlight.js
:tabsize: 4
//ctrl + shift + p y escribimos asciidoc y preview.

= Introducción

El trabajo práctico consiste en el modelado del conjunto de datos que se usa para almacenar la información relativa a una tarjeta de créditos, con la excepción de que todo se realiza en solo pago. Además no existen las extensiones pero una persona puede tener más de una tarjeta. Se deberán crear las tablas respetando el modelo estipulado, se deberán agregar las PK’s y FK’s de todas las tablas, por separado de la creación de las
tablas. Además, el usuario deberá tener la posibilidad de borrar todas las PK’s y FK’s, si lo desea. 
El trabajo deberá incluir los siguientes stored procedures ó triggers:

- *Autorización de Compra* se deberá incluir la lógica que reciba los datos de una
  compra y que devuelva *true* si se autoriza la compra ó *false* si se rechaza. Deberá validar los siguientes elementos antes de autorizar:
  * Que el número de tarjeta exista y este vigente de lo contrario cargar un rechazo.
  * Que el código de seguridad sea el correcto, de lo contrario se debe
  cargar un rechazo.
  * Que el monto total de compras pendientes de pago más la compra a realizar no
  supere el límite de la tarjeta, de lo contrario, se debe cargar
  un rechazo. 
  *Que la tarjeta no se encuentre vencida, de lo contrario, se debe cargar
  un rechazo.
  *Que la tarjeta no se encuentre suspendida, de lo contrario, se debe cargar
  un rechazo.

- *Generación del Resumen* deberá contener la lógica que reciba
  como parámetros el número de cliente, y el periodo del año, y que guarde en las
  tablas que corresponda los datos del resumen con la información pertinente.

- *Alertas a Clientes* deberá proveer la lógica que genere alertas por
  posibles fraudes de forma automática con cierta frecuencia, se pide detectar
  y almacenar las siguientes alertas.
  * Todo rechazo se debe ingresar automáticamente en el mismo instante en que se generó a la tabla de alertas.
  * Si una tarjeta registra dos compras en un lapso menor de un minuto en comercios
  distintos ubicados en el mismo código postal..
  * i una tarjeta registra dos compras en un lapso menor de 5 minutos en comercios
  con diferentes códigos postales.
  * Si una tarjeta registra dos rechazos por exceso de límite en el mismo día, la tarjeta tiene que ser suspendida preventivamente, y se debe grabar una alerta asociada a este cambio de estado.

Por úlimo, para poder comparar el modelo relacional con un modelo no relacional *NoSQL*, se pide guardar los datos de clientes, tarjetas, comercios, y compras (tres por cada entidad) en una base de datos *NoSQL basada en JSON*. Para ello, utilizar la base de datos *BoltDB*.

*Todo el código SQL escrito en este trabajo , deberá poder ejecutarse
desde una aplicación CLI escrita en Go.*

= Descripción

La aplicación se desarrolló en Go un lenguaje de programación nuevo para nosotros. Una de las dificultades que se presentó fue el hecho de tener que realizar por cada carpeta un solo archivo y ese archivo debía tener el mismo nombre que la carpeta. Se demoró en resolver esta dificultad, acostumbrados nosotros a dividir los proyectos en vista, modelo y datos, esta vez nos quedaron más carpetas que se corresponden bajo una misma responsabilidad.

Para cumplir con el requerimiento de una interfaz de línea de comando se decidió realizar un menu con el cual se intercactúa a través del ingreso de opciones basados en números. Esta acción permite al usuario realizar todas las acciones dsponibles en la aplicación. El problema que surgió fue la dificultad a la hora de realizar las importaciones, ya que el menu requería para el funcionamiento la interacción entre varios archivos y la manera de invocarlos resultó bastante extraña. 

= Implementación

=== Interfaz de Usuario

La aplicación se desarrollo mediante la implementación de un menu compuesto de diferentes funcionalidades con nombres declarativos donde predominan las sentencias switch. De esta manera se controla la opción ingresada por el usuario y se realiza el llamado a la función indicada, esa es la lógica predominante en esta parte. 

.A continuación se incluye parte del código que contiene el comportamiento del menú.
[source, go]
----

		opcionConsumo()
	case 2:
		consumo.Resetear()
		UI.Esperar(2)
		opcionConsumo()
	case 3:
		Inicio()
	case 4:
		salir()
	default:
		msjAuxiliar("Debe ingresar una opción correcta")
		opcionConsumo()
	}
}

////////// INTERFAZ DE USUARIO //////////

// Muestra el menú principal de la aplicación
func principal() int {
	var eleccion int
	UI.Clean()
	UI.BloqueDeTexto("*", "Menú principal")
	fmt.Print(`
	Seleccione la opción numérica deseada:

	1 --> Gestionar base de datos
	2 --> Gestionar tablas
	3 --> Insertar datos
	4 --> Insertar funciones
	5 --> Gestionar consumos
	-----------------------------
	6 --> Salir
	`)
	fmt.Print("\n	Opción: ")
	fmt.Scanf("%d\n", &eleccion)
	return eleccion
}

// Muestra el submenú para gestionar la BBDD
func bbdd() int {
	var eleccion int
	UI.Clean()
	UI.BloqueDeTexto("*", "Gestionar base de datos")
	fmt.Print(`
	Seleccione la opción numérica deseada:

	1 --> Crear una base de datos
	2 --> Eliminar una base de datos
	3 --> Renombrar una base de datos
	----------------------------------
	4 --> Volver al menú principal
	5 --> Salir
	`)
	fmt.Print("\n	Opción: ")
	fmt.Scanf("%d\n", &eleccion)
	return eleccion
}
----

=== Código Relacionado con la Base de Datos

.Aquí se detalla parte del código para la manipulación por parte del usuario de todo lo relacionado a la base de datos. Todas estas funciones son llamadas a través del menu.
[source, go]
----

//Crear : Crea una BBDD
func Crear() {
	//Se crea el string con los datos para acceder a postgres
	psqlInfo := fmt.Sprintf("host=%s port=%d user=%s password=%s sslmode=disable",
		host, port, user, password)

	// Entramos a postgres
	db, err := sql.Open("postgres", psqlInfo)
	if err != nil {
		panic(err)
	}
	defer db.Close()

	//Se procede a la creación de la base de datos
	fmt.Print("\n\tIngrese el nombre de la base de datos que desea crear: ")
	var dbname string
	fmt.Scanf("%s", &dbname)

	_, err = db.Exec("CREATE DATABASE " + dbname)
	if err != nil {
		//Agregar logica para dar msj si la base de datos ya existe
		fmt.Println("\n	", err)
	} else {

		//Procedemos a hacerle ping para asegurarnos que todo salió bien

		//Se crea el string con los datos para acceder a la base de daos creada
		psqlInfo = fmt.Sprintf("host=%s port=%d user=%s password=%s dbname=%s sslmode=disable",
			host, port, user, password, dbname)

		//Abrimos la base de datos
		db, err = sql.Open("postgres", psqlInfo)
		if err != nil {
			panic(err)
		}

		defer db.Close()

		//Le hacemos ping
		err = db.Ping()
		if err != nil {
			panic(err)
		}

		fmt.Printf("\n\tLa base de datos %s, se creó exitosamente!", dbname)
	}

}

// Eliminar : Elimina una base de datos
func Eliminar() {

	//Se crea el string con los datos para acceder a postgres
	psqlInfo := fmt.Sprintf("host=%s port=%d user=%s password=%s sslmode=disable",
		host, port, user, password)

	// Entramos a postgres
	db, err := sql.Open("postgres", psqlInfo)
	if err != nil {
		panic(err)
	}
	defer db.Close()

	//Se solicita el nombre de la base de datos a eliminar
	fmt.Print("\n\tIngrese el nombre de la base de datos que desea eliminar: ")
	var dbname string
	fmt.Scanf("%s", &dbname)

	//Se procede a eliminar
	_, err = db.Exec("DROP DATABASE " + dbname)
	if err != nil {
		// Agregar lógica para dar msj si la base de datos no existe
		fmt.Println("\n	", err)
	} else {
		fmt.Println("\n\tSe eliminó la base de datos " + dbname)
	}
}

// Renombrar : Renombra una base de datos
func Renombrar() {

	//Se crea el string con los datos para acceder a postgres
	psqlInfo := fmt.Sprintf("host=%s port=%d user=%s password=%s sslmode=disable",
		host, port, user, password)

	// Entramos a postgres
	db, err := sql.Open("postgres", psqlInfo)
	if err != nil {
		panic(err)
	}
	defer db.Close()

	//Se solicita el nombre de la base de datos a renombrar
	fmt.Print("\n\tIngrese el nombre de la base de datos que desea renombrar: ")
	var dbnameOld string
	fmt.Scanf("%s", &dbnameOld)

	//Se solicita el nuevo nombre
	fmt.Print("\n\tIngrese el nuevo nombre para la base de datos: ")
	var dbnameNew string
	fmt.Scanf("%s", &dbnameNew)

	//Se procede a renombrar
	_, err = db.Exec("ALTER DATABASE " + dbnameOld + " RENAME TO " + dbnameNew)
	if err != nil {
		// Agregar lógica para dar msj si la base de datos no existe
		fmt.Println("\n	", err)
	} else {
		fmt.Println("\n\tSe realizó el cambio " + dbnameOld + " --> " + dbnameNew)
	}
}

----

=== Trigger para la Autorización de Compra

La idea es que la función de forma automatica, a través de las sentencias condicionales que contiene evalue los diferentes campos críticos de la tarjeta y según sus valores permita la compra e inserte la información en las tablas correspondientes. O de lo contrario, envíe los datos a la sección de rechazos.

.En esta sección se detalla la codificación del trigger que se encarga de la autorización de cada compra.
[source, go]

----

// AutorizacionCompra : Verifica si una compra es posible y devuelve un booleano
func AutorizacionCompra() {
	//Se procede a la conexión de la base de datos
	fmt.Print("\n\tIngrese el nombre de la base de datos: ")
	var dbname string
	fmt.Scanf("%s", &dbname)

	//Se crea el string con los datos para acceder a la base de datos
	psqlInfo := fmt.Sprintf("host=%s port=%d user=%s password=%s dbname=%s sslmode=disable",
		host, port, user, password, dbname)

	//Probar si funciona esto: SELECT 1 WHERE nrotarjeta_recibido IN(SELECT nrotarjeta FROM tarjeta WHERE estado = 'vigente')

	//Abrimos la base de datos
	db, err := sql.Open("postgres", psqlInfo)
	defer db.Close()
	if err != nil {
		fmt.Println("\n	", err)
	} else {
		_, err = db.Exec(`CREATE OR REPLACE FUNCTION compra_valida() RETURNS TRIGGER AS $$

		DECLARE

			existe int;
			codigo_valido int;
			suma_consumos_previos decimal(8,2);
			limite decimal(8,2);
			vencida int;
			suspendida int;
			
		BEGIN

			--Inicialización de variales:

			SELECT COUNT(nrotarjeta) INTO existe FROM tarjeta
				WHERE NEW.nrotarjeta = nrotarjeta AND estado = 'vigente';

			SELECT COUNT(codseguridad) INTO codigo_valido FROM tarjeta
				WHERE NEW.nrotarjeta = nrotarjeta AND NEW.codseguridad = codseguridad;

			SELECT SUM(monto) INTO suma_consumos_previos FROM compra
				WHERE pagado = FALSE AND nrotarjeta = NEW.nrotarjeta;


			SELECT limitecompra INTO limite FROM tarjeta
				WHERE NEW.nrotarjeta = nrotarjeta;

			SELECT COUNT(nrotarjeta) INTO vencida FROM tarjeta
				WHERE NEW.nrotarjeta = nrotarjeta AND ( current_date < to_date(tarjeta.validadesde, 'YYYYMM') OR current_date > to_date(tarjeta.validahasta, 'YYYYMM') );

			SELECT COUNT(nrotarjeta) INTO suspendida FROM tarjeta
			WHERE NEW.nrotarjeta = nrotarjeta AND estado = 'suspendida';

			--Validación de datos:

			IF existe THEN
				IF codigo_valido THEN
					IF vencida = 0 THEN
						IF suspendida = 0 THEN
							IF (NEW.monto > limite) OR (suma_consumos_previos + NEW.monto > limite) THEN
								INSERT INTO rechazo(nrotarjeta, nrocomercio, fecha, monto, motivo)
								VALUES(
									NEW.nrotarjeta,
									NEW.nrocomercio,
									CURRENT_TIMESTAMP,
									NEW.monto,
									'supera límite de tarjeta'   
								);	
									
							ELSE INSERT INTO compra(nrotarjeta, nrocomercio, fecha, monto, pagado)
								VALUES(
									NEW.nrotarjeta,
									NEW.nrocomercio,
									CURRENT_TIMESTAMP,
									NEW.monto,
									FALSE
								);
																					
							END IF;

						ELSE INSERT INTO rechazo(nrotarjeta, nrocomercio, fecha, monto, motivo)
							VALUES(
								NEW.nrotarjeta,
								NEW.nrocomercio,
								CURRENT_TIMESTAMP,
								NEW.monto,
								'la tarjeta se encuentra suspendida'
							);
							
						END IF;

					ELSE INSERT INTO rechazo(nrotarjeta, nrocomercio, fecha, monto, motivo)
						VALUES(
							NEW.nrotarjeta,
							NEW.nrocomercio,
							CURRENT_TIMESTAMP,
							NEW.monto,
							'plazo de vigencia expirado'
						);

					END IF;

				ELSE INSERT INTO rechazo(nrotarjeta, nrocomercio, fecha, monto, motivo)
					VALUES(
						NEW.nrotarjeta,
						NEW.nrocomercio,
						CURRENT_TIMESTAMP,
						NEW.monto,
						'código de seguridad inválido'
					);
								
				END IF;

			ELSE INSERT INTO rechazo(nrotarjeta, nrocomercio, fecha, monto, motivo)
				VALUES(
					NEW.nrotarjeta,
					NEW.nrocomercio,
					CURRENT_TIMESTAMP,
					NEW.monto,
					'tarjeta no válida ó no vigente'
				);

			END IF;
			RETURN NULL;
		END;
		$$ LANGUAGE plpgsql;`)

		if err != nil {
			fmt.Println("\n	", err)
		} else {
			_, err = db.Exec(`CREATE TRIGGER compra_valida_trg
				AFTER INSERT ON consumo
				FOR EACH ROW
				EXECUTE PROCEDURE compra_valida();`)

			if err != nil {
				fmt.Println("\n	", err)
			} else {
				fmt.Println("stored procedure Y trigger para la autorización de compra, agregada")
			}
		}
	}
}
----

=== Procedimiento para la generación del resumen de tarjetas.

El procedimiento para generar el resumen primero verifica las tarjetas que posee un cliente determinado, se guardan los datos del individuo y del instrumento financiero en variables de tipo record, esta inforamción luego es agregada a la cabecera del resumen. El procedimienro continúa con la revisión de las compras realizadas con la tarjeta archivando los comercios en donde fue realizada. Se realiza la suma y se va incrementando la línea del resumen. Todo esto se realiza mediante un ciclo. La siguiente función se encarga de insertar los resúmenes en la base de datos y el último método permite elegir un cliente determinado para visualizar un resúmen.

.En este apartado se muestra el código que maneja la lógica sobre la generación de los resúmenes de las tarjetas.
[source, go]

----

// generación del resumen el trabajo práctico deberá contener la lógica que reciba
// como parámetros el número de cliente, y el periodo del año, y que guarde en las
// tablas que corresponda los datos del resumen con la siguiente información: nombre
// y apellido, dirección, número de tarjeta, periodo del resumen, fecha de vencimiento,
// todas las compras del periodo, y total a pagar.

// GenerarResumen : Inserta un nuevo resumen
func GenerarResumen() {
	//Se procede a la conexión de la base de datos
	fmt.Print("\n\tIngrese el nombre de la base de datos: ")
	var dbname string
	fmt.Scanf("%s", &dbname)

	//Se crea el string con los datos para acceder a la base de datos
	psqlInfo := fmt.Sprintf("host=%s port=%d user=%s password=%s dbname=%s sslmode=disable",
		host, port, user, password, dbname)

	//Abrimos la base de datos
	db, err := sql.Open("postgres", psqlInfo)
	defer db.Close()
	if err != nil {
		fmt.Println("\n	", err)
	} else {

		//Se crea el procedimiento almacenado
		_, err = db.Exec(`
		CREATE OR REPLACE FUNCTION resumen(nrocliente_recibido int, desde char(8), hasta char(8)) RETURNS void AS $$

		DECLARE
		
			nrocabecera int;
			fecha_desde date;
			fecha_hasta date;
			fecha_vencimiento date;
			i record;
			j record;
			linea_actual int;
			fila_tarjeta record;
			nombre_comercio text;
			cliente_temporal record;
			suma_total decimal(7,2);
		
		BEGIN
		
			linea_actual := 1;
			
			fecha_desde := to_date(desde, 'YYYYMMDD');
			fecha_hasta := to_date(hasta, 'YYYYMMDD');
			fecha_vencimiento := to_date(hasta, 'YYYYMMDD') + 10;
		
			--Para cada tarjeta del cliente (puede tener más de una)
			FOR i IN SELECT * FROM tarjeta WHERE(tarjeta.nrocliente = nrocliente_recibido) loop
		
				suma_total := 0;
		
				--Se verifica la tarjeta. Si existe, se guarda la fila completa
				SELECT * INTO fila_tarjeta FROM tarjeta WHERE i.nrotarjeta = nrotarjeta;
				IF FOUND THEN
					
					--Se guarda al cliente con todos sus datos
					SELECT * INTO cliente_temporal FROM cliente WHERE(nrocliente = fila_tarjeta.nrocliente);
				   
					--Agregamos todos los datos obtenidos a la cabecera
					INSERT INTO cabecera(nombre, apellido, domicilio, nrotarjeta, desde, hasta, vence, total) 
					VALUES (cliente_temporal.nombre, cliente_temporal.apellido, cliente_temporal.domicilio, fila_tarjeta.nrotarjeta, fecha_desde, fecha_hasta, fecha_vencimiento, suma_total); 
				   
					--Guardamos el número mayor de cabecera, después de la inserción
					SELECT MAX(nroresumen) INTO nrocabecera FROM cabecera;
				  
				   -- SELECT count(*) INTO cabecera_id  FROM cabecera;
						
					--Se revisan todas las compras de ese cliente con esa tarjeta
					FOR j IN SELECT * FROM compra WHERE (compra.nrotarjeta = fila_tarjeta.nrotarjeta AND compra.fecha <= fecha_hasta AND compra.fecha >= fecha_desde) loop
						
						--Se guardan el nombre del comercio
						SELECT nombre INTO nombre_comercio FROM comercio where(comercio.nrocomercio = j.nrocomercio);
						
						INSERT INTO detalle VALUES (nrocabecera, linea_actual, j.fecha, nombre_comercio, j.monto);
						
						suma_total = suma_total + j.monto;
		
						linea_actual := linea_actual + 1;
					
					end loop;
		
					--Se actualiza 
					UPDATE cabecera SET total = suma_total WHERE (nroresumen = nrocabecera);
				   
				ELSE
					 RAISE NOTICE 'Error en la solicitud, verifique los datos ingresados';
					
				END IF;
			end loop;    
		END;
		$$ language plpgsql;
		`)
		if err != nil {
			fmt.Println("\n	", err)
		} else {

			fmt.Println("\n\tProcedimiento almacenado para la generación de resumen, agregado")

		}
	}
}
// Resumen : Inserta el
func Resumen() {
	//Se procede a la conexión de la base de datos
	fmt.Print("\n\tIngrese el nombre de la base de datos: ")
	var dbname string
	fmt.Scanf("%s", &dbname)

	//Se crea el string con los datos para acceder a la base de datos
	psqlInfo := fmt.Sprintf("host=%s port=%d user=%s password=%s dbname=%s sslmode=disable",
		host, port, user, password, dbname)

	//Abrimos la base de datos
	db, err := sql.Open("postgres", psqlInfo)
	defer db.Close()
	if err != nil {
		fmt.Println("\n	", err)
	} else {

		//Se obtienen los datos que recibirá el procedimiento almacenado
		var nrocliente int
		var desde string
		var hasta string

		nrocliente = elegirCliente(db)
		if nrocliente != 0 {
			UI.Clean()
			fmt.Print("\n\tIngrese la fecha de inicio en el formato (YYYYMMDD) Ejemplo --> 20190610: ")
			fmt.Scanf("%s", &desde)

			fmt.Print("\n\tIngrese la fecha de fin en el formato (YYYYMMDD) Ejemplo --> 20190710: ")
			fmt.Scanf("%s", &hasta)

			if desde > hasta {
				fmt.Println("\n\tLa fecha de inicio es mayor a la de fin!")
			} else {
				//Se prepara la consulta
				sqlStatement := `SELECT resumen($1, $2, $3)`
				_, err = db.Exec(sqlStatement, nrocliente, desde, hasta)
				if err != nil {
					fmt.Println("\n\t	", err)
				} else {
					fmt.Println("\n\tSe ha creado el resumen a partir del stored procedures --> resumen")

					//verResumen();
				}
			}
		} else {
			fmt.Println("\n\tError al elegir el cliente de la lista!")
		}
	}
}

////////////////////////////////////////////////////////////////////////////////////

func elegirCliente(db *sql.DB) int {
	UI.Clean()
	type Cliente struct {
		nrocliente int
		nombre     string
		apellido   string
	}
	rows, err := db.Query(`SELECT nrocliente, nombre, apellido FROM cliente`)
	if err != nil {
		fmt.Println("\n\t", err)
		return 0
	}
	defer rows.Close()
	contador := 1
	var lista []Cliente
	UI.BloqueDeTexto("*", "Seleccionar el Cliente: ")
	for rows.Next() {
		cliente := Cliente{}
		err = rows.Scan(&cliente.nrocliente, &cliente.nombre, &cliente.apellido)
		if err != nil {
			fmt.Println("\n\t", err)
			return 0
		}
		lista = append(lista, cliente)
		fmt.Printf("%d --> Nro: %v | Apellido y nombre: %v, %v\n", contador, lista[contador-1].nrocliente, lista[contador-1].nombre, lista[contador-1].apellido)
		contador++
	}
	err = rows.Err()
	if err != nil {
		fmt.Println("\n\t", err)
		return 0
	}
	//Seleccionar el cliente
	var nroclienteElegido int
	fmt.Print("\n\tOpción: ")
	fmt.Scanf("%d\n", &nroclienteElegido)

	if nroclienteElegido <= 0 || nroclienteElegido > contador { //Si no es uno de los números de la lista
		return 0
	}

	return lista[nroclienteElegido-1].nrocliente
}

----
 
=== Procedimiento y Trigger para Alertas a Clientes

Este método se encarga de ante cualquier operación que haya sido rechazada lo refleja en la tabla de alertas de forma automática e inmediata. 

----

// Alertas : Crea el procedimiento almacenado y trigger para gestionar alertas
func Alertas() {
	//Se procede a la conexión de la base de datos
	fmt.Print("\n\tIngrese el nombre de la base de datos: ")
	var dbname string
	fmt.Scanf("%s", &dbname)

	//Se crea el string con los datos para acceder a la base de datos
	psqlInfo := fmt.Sprintf("host=%s port=%d user=%s password=%s dbname=%s sslmode=disable",
		host, port, user, password, dbname)

	//Abrimos la base de datos
	db, err := sql.Open("postgres", psqlInfo)
	defer db.Close()
	if err != nil {
		fmt.Println("\n	", err)
	} else {

		//Se crea el procedimiento almacenado
		_, err = db.Exec(`
			CREATE OR REPLACE FUNCTION rechazo() RETURNS TRIGGER AS $$
			DECLARE 
			BEGIN
				
				INSERT INTO alerta (nrotarjeta, fecha, nrorechazo, codalerta, descripcion) 
				VALUES (NEW.nrotarjeta, NEW.fecha, NEW.nrorechazo, 2, NEW.motivo);
				RETURN NEW;
			END;
			$$ LANGUAGE plpgsql;

			----------TRIGGER------------

			CREATE TRIGGER rechazo_trg
				AFTER INSERT ON rechazo
				FOR EACH ROW
					EXECUTE PROCEDURE rechazo();
					
			--------------------------------------------------------------------------------------------
			--------------------------------------------------------------------------------------------
			
			CREATE OR REPLACE FUNCTION compras_consecutivas_1minuto() RETURNS TRIGGER AS $$
			DECLARE

				compra_consecutiva_1minuto record;
				cp_comercio char(8);
				codigo_alerta int;

			BEGIN
				codigo_alerta := 1000; --Se elige el tiempo de 1 minuto en milisegundos como código de alerta

				SELECT codigopostal INTO cp_comercio FROM comercio WHERE nrocomercio = NEW.nrocomercio;

				SELECT * INTO compra_consecutiva_1minuto FROM compra
				WHERE 
					NEW.nrotarjeta = compra.nrotarjeta --misma tarjeta
					AND NEW.fecha > ( NOW() - 1 * INTERVAL '1 minute' ) --en menos de un minuto
					AND NEW.nrocomercio NOT IN(SELECT nrocomercio FROM compra WHERE nrotarjeta = NEW.nrotarjeta) --en diferentes comercios
					AND cp_comercio IN (SELECT codigopostal FROM comercio WHERE nrocomercio = compra.nrocomercio); --en el mismo cod postal

				IF FOUND THEN
					INSERT INTO alerta(nrotarjeta, fecha, codalerta, descripcion)
					VALUES(
						NEW.nrotarjeta,
						NEW.fecha,
						codigo_alerta,
						'Compras consecutivas en lapso menor a 1 minuto, en diferentes comercios, en el mismo código postal'
					);
				END IF;
				RETURN NEW;
			END;
			$$ LANGUAGE plpgsql;

			----------TRIGGER------------

			CREATE TRIGGER compras_consecutivas_1minuto_trg
				BEFORE INSERT ON compra
				FOR EACH ROW
					EXECUTE PROCEDURE compras_consecutivas_1minuto();
			
			--------------------------------------------------------------------------------------------
			--------------------------------------------------------------------------------------------
			
			CREATE OR REPLACE FUNCTION compras_consecutivas_5minutos() RETURNS TRIGGER AS $$
			DECLARE
				compra_consecutiva_5minutos record;
				cp_comercio char(8);
				codigo_alerta int;
			BEGIN
				codigo_alerta := 5000; --Se elige el tiempo de 5 minutos en milisegundos como código de alerta

				SELECT codigopostal INTO cp_comercio FROM comercio WHERE nrocomercio = NEW.nrocomercio;

				SELECT * INTO compra_consecutiva_5minutos FROM compra
				WHERE 
					NEW.nrotarjeta = compra.nrotarjeta --misma tarjeta
					AND NEW.fecha > ( NOW() - 5 * INTERVAL '1 minute' ) --en menos de 5 minutos
					AND NEW.nrocomercio NOT IN(SELECT nrocomercio FROM compra WHERE nrotarjeta = NEW.nrotarjeta) --en diferentes comercios
					AND cp_comercio NOT IN (SELECT codigopostal FROM comercio WHERE nrocomercio = compra.nrocomercio); --en el distintos cod postales

				IF FOUND THEN
					INSERT INTO alerta(nrotarjeta, fecha, codalerta, descripcion)
					VALUES(
						NEW.nrotarjeta,
						NEW.fecha,
						codigo_alerta,
						'Compras consecutivas en lapso menor a 5 minutos, en diferentes comercios, con distinto código postal'
					);
				END IF;
				RETURN NEW;
			END;
			$$ LANGUAGE plpgsql;

			----------TRIGGER------------

			CREATE TRIGGER compras_consecutivas_5minutos_trg
				BEFORE INSERT ON compra
				FOR EACH ROW
					EXECUTE PROCEDURE compras_consecutivas_5minutos();

			--------------------------------------------------------------------------------------------
			--------------------------------------------------------------------------------------------
			
			CREATE OR REPLACE FUNCTION compras_rechazadas_limite() RETURNS TRIGGER AS $$
			DECLARE
				fila_rechazo record;
				codigo_alerta int;
				--fecha_nueva_anio date;
				--fecha_nueva_mes date;
				--fecha_nueva_dia date;
			
			BEGIN
				codigo_alerta := 2; --Se elige como código el número de rechazos por exceso de límite

                --Se extraen de la fecha de rechazo timestamp solo el año, mes y día
                --SELECT EXTRACT(YEAR FROM NEW.fecha) INTO fecha_nueva_anio;	
                --SELECT EXTRACT(MONTH FROM NEW.fecha) INTO fecha_nueva_mes;
                --SELECT EXTRACT(DAY FROM NEW.fecha) INTO fecha_nueva_dia;
                
				
                SELECT * INTO fila_rechazo FROM rechazo
				WHERE
					NEW.nrotarjeta = rechazo.nrotarjeta
                    --Comparamos con otros rechazos, para ver si se dio el mismo año, mes, día
					--AND fecha_nueva_anio = EXTRACT(YEAR FROM rechazo.fecha)
                    --AND fecha_nueva_mes = EXTRACT(MONTH FROM rechazo.fecha)
					--AND fecha_nueva_dia = EXTRACT(DAY FROM rechazo.fecha)
					AND cast(new.fecha as date) = cast(rechazo.fecha as date)
					AND NEW.motivo = rechazo.motivo
					AND NEW.motivo = 'supera límite de tarjeta';
				
				IF FOUND THEN
					UPDATE tarjeta SET estado='suspendida' WHERE nrotarjeta = NEW.nrotarjeta;

					INSERT INTO alerta(nrotarjeta, fecha, codalerta, descripcion)
					VALUES(
						NEW.nrotarjeta,
						NEW.fecha,
						codigo_alerta,
						'Suspensión de tarjeta por exceder dos veces el límite, el mismo día'
					);
				END IF;

				RETURN NEW;

			END;
			$$ LANGUAGE plpgsql;

			CREATE TRIGGER compras_rechazadas_limite_trg
			BEFORE INSERT ON rechazo
			FOR EACH ROW
				EXECUTE PROCEDURE compras_rechazadas_limite();`)
		if err != nil {
			fmt.Println("\n	", err)
		} else {

			fmt.Println("\n\tProcedimientos almacenados y triggers para la gestión de alertas, agregados")

		}
	}
}
----

=== JSON y Bases de datos NoSQL

En esta parte primero creamos las estructuras que más tarde utilizaremos para el manejo de los datos con Json. Después se encuentran las funciones para crear una base de datos Nosql, la escritura y la lectura de la información tal como se ha visto en clases. Luego se desarrollo el método para poder ingresar información a la base y la última corresponde a la visualización de los datos ingresados a través de la función de lectura mencionada antes.

.A continuación se detallará el código que se encarga del manejo de una base de datos no relacional. 
[source, go]

----

type Cliente struct {
    Nrocliente int
	Nombre string
	Apellido string
	Domicilio string
	Telefono string
}

type Tarjeta struct {
    Nrotarjeta string
	Nrocliente int
	Validadesde string
	Validahasta string
	Codseguridad string
	Limitecompra float64
	Estado string 
}

type Comercio struct {
    Nrocomercio int
	Nombre string
	Domicilio string
	Codigopostal string
	Telefono string
}

type Compra struct {
	Nrooperacion  int
	Nrotarjeta string
	Nrocomercio int
	Fecha time.Time
	Monto float64
	Pagado bool
}

func CrearBdNosql(nombre string) *bolt.DB {
	bd, error := bolt.Open(nombre, 0600, nil)
	if error != nil {
		log.Fatal(error)	
	}
	return bd
}

func escritura(bd *bolt.DB, nombreBucket string, llave []byte, valor []byte) error {
	//se abre una transacción de escritura.
    transcc, error := bd.Begin(true) //me devuelve una transaccion.
    if error != nil {
        return error
    }
    defer transcc.Rollback()//metodo que controla consistencia y cierra transaccion.

	//creo el backet con el nombre que me pasaron
	backet, _ := transcc.CreateBucketIfNotExists([]byte(nombreBucket))

    error = backet.Put(llave, valor)//se coloca el valor asociado.
    if error != nil {
        return error
    }
    //se cierra la transacción de escritura.
    if error := transcc.Commit(); error != nil {//se guardan los datos
        return error
    }
    return nil
}

//funcion que lee un solo valor debe recibir como key algo como una pk.
func lecturaUnica(bd *bolt.DB, nombreBucket string, llave []byte) ([]byte, error) {

    var buffer []byte //slice de bytes para valor de retorno

	// abre una transacción de lecturaUnica con la func View que espera como param 
	// otra func y controla esa transaccion.(rollback, commit).
    error := bd.View(func(transcc *bolt.Tx) error {

		//se pasa el bck a slice, es decir, busca el bck del nombre ej alumno.
		backet := transcc.Bucket([]byte(nombreBucket))
		
		// a ese bck le pido el valor ej legajo y la guardo para devolverlo.
		buffer = backet.Get(llave)
		
        return nil
    })
    return buffer, error
}

func poblarDatos(bd *bolt.DB){
	//los clientes para agregar a la backet
	julia := Cliente{4781, "Julia", "Montiel", "Paraguay 778","4657-1866"}
    data, error := json.Marshal(julia)
    if error != nil {
        log.Fatal(error)
	}
	escritura(bd, "cliente", []byte(strconv.Itoa(julia.Nrocliente)), data)

	juan := Cliente{4975, "Juan", "Melgarejo", "Chacabuco 465","4738-4823"}
    data, error = json.Marshal(juan)
    if error != nil {
        log.Fatal(error)
	}
	escritura(bd, "cliente", []byte(strconv.Itoa(juan.Nrocliente)), data)

	romina := Cliente{4807, "Romina", "Guerreiro", "Lacroze 1533","1534888006"}
    data, error = json.Marshal(romina)
    if error != nil {
        log.Fatal(error)
	}
	escritura(bd, "cliente", []byte(strconv.Itoa(romina.Nrocliente)), data)

	//las tarjetas para agregar
	tarjeta1:= Tarjeta{"5175847480130436",julia.Nrocliente,"201612","202612","0489",27342,"vigente"}
	data, error = json.Marshal(tarjeta1)
	if error !=nil{
		log.Fatal(error)
	}
	escritura(bd, "tarjeta", []byte(tarjeta1.Nrotarjeta), data)

	tarjeta2:= Tarjeta{"5239202881623321",juan.Nrocliente,"201210","202211","6310",20000,"vigente"}
	data, error = json.Marshal(tarjeta2)
	if error !=nil{
		log.Fatal(error)
	}
	escritura(bd, "tarjeta", []byte(tarjeta2.Nrotarjeta), data)

	tarjeta3:= Tarjeta{"4754982137770169",romina.Nrocliente,"201204","202205","0778",10750,"vigente"}
	data, error = json.Marshal(tarjeta3)
	if error !=nil{
		log.Fatal(error)
	}
	escritura(bd, "tarjeta", []byte(tarjeta3.Nrotarjeta), data)

	//los comercios para insertar
	calzados:= Comercio{59335,"Vallejo Calzados","Callao 6643","b6740fda","4638-9813"}
	data, error = json.Marshal(calzados)
	if error !=nil{
		log.Fatal(error)
	}
	escritura(bd, "comercio", []byte(strconv.Itoa(calzados.Nrocomercio)), data)

	moda:= Comercio{14910,"Full Moda","Alem 3062","b1669fda","9351-6043"}
	data, error = json.Marshal(moda)
	if error !=nil{
		log.Fatal(error)
	}
	escritura(bd, "comercio", []byte(strconv.Itoa(moda.Nrocomercio)), data)

	tech:= Comercio{26782,"Mundo Tech","Indios 4289","b1862fda","4642-8374"}
	data, error = json.Marshal(tech)
	if error !=nil{
		log.Fatal(error)
	}
	escritura(bd, "comercio", []byte(strconv.Itoa(tech.Nrocomercio)), data)

	//Listado de Compras
	fecha := time.Now()
	comprauno:= Compra{45042,tarjeta1.Nrotarjeta,tech.Nrocomercio,fecha,18000,true}
	data, error = json.Marshal(comprauno)
	if error !=nil{
		log.Fatal(error)
	}
	escritura(bd, "compra", []byte(strconv.Itoa(comprauno.Nrooperacion)), data)

	fecha = time.Now()
	comprados:= Compra{50467,tarjeta2.Nrotarjeta,calzados.Nrocomercio,fecha,8500,false}
	data, error = json.Marshal(comprados)
	if error !=nil{
		log.Fatal(error)
	}
	escritura(bd, "compra", []byte(strconv.Itoa(comprados.Nrooperacion)), data)

	fecha = time.Now()
	compratres:= Compra{60987,tarjeta3.Nrotarjeta,moda.Nrocomercio,fecha,9870,true}
	data, error = json.Marshal(compratres)
	if error !=nil{
		log.Fatal(error)
	}
	escritura(bd, "compra", []byte(strconv.Itoa(compratres.Nrooperacion)), data)
}

//Mostrar Datos en Pantalla
func imprimirDatos(bd *bolt.DB){
	
	fmt.Printf("Los Clientes que han sido Ingresados son:\n\n")
	valor, _ := lecturaUnica(bd, "cliente", []byte(strconv.Itoa(4781)))
	fmt.Printf("%s\n", valor)
	valor, _ = lecturaUnica(bd, "cliente", []byte(strconv.Itoa(4975)))
	fmt.Printf("%s\n", valor)
	valor, _ = lecturaUnica(bd, "cliente", []byte(strconv.Itoa(4807)))
	fmt.Printf("%s\n\n", valor)

	fmt.Printf("Las Tarjetas Ingresadas son:\n\n")
	valor, _ = lecturaUnica(bd, "tarjeta", []byte("5175847480130436"))
	fmt.Printf("%s\n", valor)
	valor, _ = lecturaUnica(bd, "tarjeta", []byte("5239202881623321"))
	fmt.Printf("%s\n", valor)
	valor, _ = lecturaUnica(bd, "tarjeta", []byte("4754982137770169"))
	fmt.Printf("%s\n\n", valor)

	fmt.Printf("Los Comercios Ingresados son:\n\n")
	valor, _ = lecturaUnica(bd, "comercio", []byte(strconv.Itoa(59335)))
	fmt.Printf("%s\n", valor)
	valor, _ = lecturaUnica(bd, "comercio", []byte(strconv.Itoa(14910)))
	fmt.Printf("%s\n", valor)
	valor, _ = lecturaUnica(bd, "comercio", []byte(strconv.Itoa(26782)))
	fmt.Printf("%s\n\n", valor)

	fmt.Printf("Las Compras Registradas son:\n\n")
	valor, _ = lecturaUnica(bd, "compra", []byte(strconv.Itoa(45042)))
	fmt.Printf("%s\n", valor)
	valor, _ = lecturaUnica(bd, "compra", []byte(strconv.Itoa(50467)))
	fmt.Printf("%s\n", valor)
	valor, _ = lecturaUnica(bd, "compra", []byte(strconv.Itoa(60987)))
	fmt.Printf("%s\n\n", valor)
}
----
   
= Conclusiones

Este trabajo resultó muy productivo en cuanto a que fue la primera vez que pudimos trabajar con la conexión de un sistema de gestión de base de datos. Además de implementarlo en un lenguaje de programación también nuevo para nosotros. Otro de los aspectos interesantes fue la implementación de lógica en la parte correspondiente a los datos, metodología que se considera como un diseño no muy aconsejable. El proceso de desarrollo resultó de una dificultad media, se tuvo que buscar información en mayor o menor medida en casi todos los puntos a desarrollar. Pero sin dudas el item en el que se invirtió más tiempo fue en los procedimientos almacenados y triggers.   

